-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Lukuvinkki CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Status CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS LukuvinkkiTag CASCADE;
